// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vehdynzdfxbacnsynvnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlaGR5bnpkZnhiYWNuc3ludm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjYxNDQsImV4cCI6MjA3NDU0MjE0NH0.OpIyDoA0cLuNZQIvvfl6GjXrsUx3ewV1kvVRekfJmzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});